FROM ricardodlc/docker-nodejs-base-image:latest
ENV TZ=America/Cancun
RUN apk add -U tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime
WORKDIR /usr/app
COPY /app/package*.json ./
RUN npm install
WORKDIR /usr/app/src
COPY /app/src/ ./
# WORKDIR /app
# RUN chmod 777 /app/init_project.sh
# RUN pip install -r ../requirements.txt
CMD [ "npm", "run", "test" ]